// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX2cS9NuZk5g5P7gFTJI9zwtt32xOPThU',
    appId: '1:354960441863:web:c3b852c5dd50f0b4d5a0a2',
    messagingSenderId: '354960441863',
    projectId: 'ci-cd-demo-d379a',
    authDomain: 'ci-cd-demo-d379a.firebaseapp.com',
    storageBucket: 'ci-cd-demo-d379a.appspot.com',
    measurementId: 'G-67FGQ4XV1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3UC9cTd-_fQgfs_vwclkjVwSeqmseQto',
    appId: '1:354960441863:android:4554a93d02dba400d5a0a2',
    messagingSenderId: '354960441863',
    projectId: 'ci-cd-demo-d379a',
    storageBucket: 'ci-cd-demo-d379a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyColKeApQ6RzW1h3lB2zOlQBEb971V3y7U',
    appId: '1:354960441863:ios:735735e105534aadd5a0a2',
    messagingSenderId: '354960441863',
    projectId: 'ci-cd-demo-d379a',
    storageBucket: 'ci-cd-demo-d379a.appspot.com',
    iosBundleId: 'com.example.ciCdDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyColKeApQ6RzW1h3lB2zOlQBEb971V3y7U',
    appId: '1:354960441863:ios:735735e105534aadd5a0a2',
    messagingSenderId: '354960441863',
    projectId: 'ci-cd-demo-d379a',
    storageBucket: 'ci-cd-demo-d379a.appspot.com',
    iosBundleId: 'com.example.ciCdDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX2cS9NuZk5g5P7gFTJI9zwtt32xOPThU',
    appId: '1:354960441863:web:2814ca1c04d4184cd5a0a2',
    messagingSenderId: '354960441863',
    projectId: 'ci-cd-demo-d379a',
    authDomain: 'ci-cd-demo-d379a.firebaseapp.com',
    storageBucket: 'ci-cd-demo-d379a.appspot.com',
    measurementId: 'G-G70CE5G001',
  );
}
