# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "fastlane upload build to AppDistribution"
  lane :distribute_apk do
    sh "flutter build apk --release --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:354960441863:android:4554a93d02dba400d5a0a2",
      firebase_cli_token: ENV["FIREBASE_TOKEN"],
      android_artifact_type:"APK",
      android_artifact_path:"../build/app/outputs/flutter-apk/app-release.apk",
      testers: "momentamimy@gmail.com",
      release_notes: "first distribution with fastlane and github actions push"
    )
  end
end
