on:
  push:
    branches:
      - master
jobs:
  distribute_firebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          distribution: 'tellium'
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'
          working-directory: android

      - name: build and distribute app
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        run: |
          fastlane android distribute_apk
        working-directory: android